### PR TITLE
Add warning about data loss

### PR DESCRIPTION
**Pull request by Hodapp87**
# PR Details

It's probably a good idea to inform users that the app cannot be trusted to actually keep their data safe.

## Type of change

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist:

- [x] My code follows the code style of this project.
- [ ] My change generates no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by chrisjonesBSU — APPROVED** [review]

**Comment by Tmp341** [comment]
App is getting changed outside of Github. I'm amazed they still keep this repo open.

**Comment by cip123** [comment]
Don't forget to rate the app on AppStore also.

**Comment by ajarang** [comment]
complain on the apple store that the license was changed without any notification. I didn't get any notification, at least.

**Comment by mobime-org** [comment]
Please be aware that we have removed certain comments containing sensitive information about individuals with whom we have no connection.

The situation has been a disaster, and we are now working on deploying the corrected source code available in the app store.

**Pull request closed without merging**
